### ISSUE TITLE
Unspecified code_sign_arg

### ISSUE THREAD

**Issue by Kudo** [adamwaite/iOS-Build-Kit#26]
Hi,

I try to build my app project with iOS-Build-Kit.
I have one issue for signing an IPA.
Checking the code at
https://github.com/adamwaite/iOS-Build-Kit/blob/master/lib/ios_build_kit/tasks/create_ipa.rb#L69
code_sign configuration is set to code_sign_arg.
However, code_sign_args does not being use at
https://github.com/adamwaite/iOS-Build-Kit/blob/master/lib/ios_build_kit/tasks/create_ipa.rb#L71

In my environment, without specified the sign, the generated IPA will have old provision information.
I guess my Xcode's provisions are outdated, but I want to update my provisions handy without Xcode.

Are there any reasons for not specifying the sign in xcrun?

**Comment by adamwaite** [comment]
Hey @Kudo. This should be sorted now. Only took me 7 months. I'll get on to your PR soon, thanks!

**Comment by Kudo** [comment]
Thanks @adamwaite.

After a little testing, I found there are still some code sign inconsistency between xcrun and xcodebuild.  For example, I use my developer provision in xcode, then during xcodebuild step, it will sign with the developer provision implicitly.  If later for xcrun code sign step, I give another different provision, when upload to app store, they will complain for inconsistency.
My workaround is to do code sign in xcodebuild step but not xcrun step.  One limitation for xcodebuild is that it only accept provision included in Xcode, i.e. Before build, we should refresh Xcode's provisions handy.

BTW, there are still some other changes from me, but the design is totally different from your, so I did not send PR for you.  Here are they and you may able to have some reference and I am likely to see if the changes can be merge in mainstream.
- 690da06 for update Decorated-* in project plist during build time, so we don't need to modify project plist in VCS(git).
- 33d0baf for Asset Catalogs support 
- ba50505 876a275 as what I mentioned to do code sign in xcodebuild.

Thank you.
